
[[redirects]]
  from = "/newTask/*"
  to = "/newTask"
  status = 200

[[redirects]]
  from = "/"
  to = "/"
  status = 200

[[redirects]]
  from = "/contacts/*"
  to = "/contacts"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard"
  status = 200

[[redirects]]
  from = "/taskList/*"
  to = "/taskList"
  status = 200